// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConverterISOparaGOD(arg1, arg2) {
  return window['go']['main']['App']['ConverterISOparaGOD'](arg1, arg2);
}

export function CopiarISO(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopiarISO'](arg1, arg2, arg3);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function ListarDispositivosCDROM() {
  return window['go']['main']['App']['ListarDispositivosCDROM']();
}

export function ListarISOs(arg1) {
  return window['go']['main']['App']['ListarISOs'](arg1);
}

export function SelecionarArquivoISO() {
  return window['go']['main']['App']['SelecionarArquivoISO']();
}

export function SelecionarDiretorio() {
  return window['go']['main']['App']['SelecionarDiretorio']();
}

export function VerificarDependencias() {
  return window['go']['main']['App']['VerificarDependencias']();
}
