// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConverterISOparaGOD(arg1:string,arg2:string):Promise<string>;

export function CopiarISO(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPlatform():Promise<string>;

export function ListarDispositivosCDROM():Promise<Array<main.DriveInfo>>;

export function ListarISOs(arg1:string):Promise<Array<string>>;

export function SelecionarArquivoISO():Promise<string>;

export function SelecionarDiretorio():Promise<string>;

export function VerificarDependencias():Promise<main.DependencyStatus>;
